### ISSUE TITLE
New landing page for apple silicon projects

### ISSUE THREAD

**Issue by wintifrosch** [armada-alliance/master#5]
I think the apple silicon hardware platform deserves a landing page like /raspi-spo/, e.g. /apple-silicon-spo/  

I will set up a staking node on a MacMini in the next weeks. I'm looking for a way to share knowledge (like how to boot ubuntu server on apple silicon) and to discuss the strategies (like libvirt and kubernetes etc.)

**Comment by AstroWa3l** [comment]
Awesome, I agree this is a great idea!
