### ISSUE TITLE
Need to fix translations

### ISSUE THREAD

**Issue by AstroWa3l** [armada-alliance/master#62]
Seems that our crowdin application is not working anymore with our repo. Not exactly what the issue is here. @rekuenkdr I am not sure but I think something broke the connection between this master repo and crowdin branch because it no longer syncs. Maybe we should just re-setup the branches again?

**Comment by rekuenkdr** [comment]
> Seems that our crowdin application is not working anymore with our repo. Not exactly what the issue is here. @rekuenkdr I am not sure but I think something broke the connection between this master repo and crowdin branch because it no longer syncs. Maybe we should just re-setup the branches again?

I will take a look at it tomorrow morning to see what the problem is and fix it.

**Comment by AstroWa3l** [comment]
Thank you my friend 🙏

**Comment by AstroWa3l** [comment]
That is a good point we are in need of some translations, I can try to get some people in our community to help us out. I might need to think of some form of incentives though, maybe make like badges/nfts or just give some tokens/ada idk.
