### ISSUE TITLE
Telgram Bot Link returns 404

### ISSUE THREAD

**Issue by rekuenkdr** [armada-alliance/master#66]
The link to the telegram bot guide inside [Environment Setup](https://github.com/armada-alliance/master/blob/54c8a3ca5b1f9542a1d8ddebfd5cf832a7ae7cfb/docs/stake-pool-guides/pi-pool-tutorial/pi-node-full-guide/environment-setup.md?plain=1#L503) is broken. (Line 503)

Broken link: https://docs.armada-alliance.com/learn/intermediate-guide/grafana-alerts-with-telegram

Replace with : https://docs.armada-alliance.com/learn/stake-pool-guides/grafana-alerts-with-telegram

**Comment by AstroWa3l** [comment]
Awesome, Thanks for finding this @rekuenkdr 👍
